version: "3"
services:
  
  front:
   build:
      context: ./front-reactjs
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: mern-front
   networks:
    -  mern-stack-net
   volumes:
    -  ./front-reactjs/src:/usr/app/src
    -  ./front-reactjs/public:/usr/app/public
   depends_on:
    - back
   stdin_open: true
   tty: true

  back:
   build:
      context: ./back
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: mern-back
   networks:
     - mern-stack-net
   volumes:
    - ./back/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local