version: "3"
services:
  
  front:
   build:
      context: ./frontend-angularjs
      dockerfile: Dockerfile.dev
   ports:
    -  4200:4200
   container_name: mean-front
   networks:
    -  mean-stack-net
   volumes:
    -  ./frontend-angularjs/src:/usr/app/src
    -  ./frontend-angularjs/public:/usr/app/public
   depends_on:
    - back
   stdin_open: true
   tty: true

  back:
   build:
      context: ./back
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: mean-back
   networks:
     - mean-stack-net
   volumes:
    - ./back/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mean-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mean-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local