version: "3"
services:
  
  front:
   build:
      context: ./frontend-mevn
      dockerfile: Dockerfile.dev
   ports:
    -  8080:8080
   container_name: mevn-front
   networks:
    -  mevn-stack-net
   volumes:
    -  ./frontend-mevn/src:/usr/app/src
    -  ./frontend-mevn/public:/usr/app/public
   depends_on:
    - back
   stdin_open: true
   tty: true

  back:
   build:
      context: ./back
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: mevn-back
   networks:
     - mevn-stack-net
   volumes:
    - ./back/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mevn-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mevn-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local